# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 09:06
from __future__ import unicode_literals

from django.db import migrations


def _create_group(name, *, apps):
    # http://stackoverflow.com/questions/22250352/in-django-how-do-you-programmatically-create-a-group-with-permissions
    Group = apps.get_model('auth', 'Group')
    group, created = Group.objects.get_or_create(name=name)
    return group


def _add_permissions_to_group(group, permissions, *, apps):
    group.permissions.add(*permissions)


def _add_users_to_group(group, users, *, apps):
    # http://stackoverflow.com/questions/31334332/giving-default-permissions-or-a-default-group-to-new-users
    for user in users:
        user.groups.add(group)


def init_default_publisher_group(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Permission = apps.get_model('auth', 'Permission')

    group = _create_group('publisher', apps=apps)
    permissions = Permission.objects.filter(
        codename__in=(
            'add_photo', 'change_photo', 'delete_photo',
            'add_rating', 'change_rating', 'delete_rating',
            'change_user', 'delete_user',
        )
    )
    users = User.objects.all()  # filter(is_superuser=0, is_stuff=0)

    _add_permissions_to_group(group, permissions, apps=apps)
    _add_users_to_group(group, users, apps=apps)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(init_default_publisher_group),
    ]
