# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-03 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_auto_20160203_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='photos.Photo'),
        ),
    ]
